### ISSUE TITLE
HTTP 422 Error / InvalidAuthenticityToken

### ISSUE THREAD

**Issue by GloktarFR** [OSC/ondemand#1193]
After a fresh installation of OOD-2.0.9 on CentOS-7.9, I'm unable to use batch connect applications.
The navigation through the dashboard (file explorer, shell, etc.) is working well though.
But every time I try to submit a job in an interactive session, I'm getting a HTTP 422 Error.

In the /var/log/ondemand-nginx/<user>/error.log, I'm seeing this error message:

```
App 19736 output: [2021-05-31 09:51:01 +0200 ]  WARN "Can't verify CSRF token authenticity."
App 19736 output: [2021-05-31 09:51:01 +0200 ]  INFO "method=POST path=/pun/sys/dashboard/batch_connect/sys/bc_desktop_3d/session_contexts format=html controller=BatchConnect::SessionContextsController action=create status=422 error='ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken' duration=0.73 view=0.00"
App 19736 output: [2021-05-31 09:51:01 +0200 ] FATAL ""
App 19736 output: [2021-05-31 09:51:01 +0200 ] FATAL "ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):"
App 19736 output: [2021-05-31 09:51:01 +0200 ] FATAL ""
App 19736 output: [2021-05-31 09:51:01 +0200 ] FATAL "actionpack (5.2.6) lib/action_controller/metal/request_forgery_protection.rb:215:in `handle_unverified_request'\nactionpack (5.2.6) lib/action_controller/metal/request_forgery_protection.rb:247:in `handle_unverified_request'\nactionpack (5.2.6) lib/action_controller/metal/request_forgery_protection.rb:242:in `verify_authenticity_token'\nactivesupport (5.2.6) lib/active_support/callbacks.rb:426:in `block in make_lambda'\nactivesupport (5.2.6) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'\nactionpack (5.2.6) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'\nactivesupport (5.2.6) lib/active_support/callbacks.rb:199:in `block in halting'\nactivesupport (5.2.6) lib/active_support/callbacks.rb:513:in `block in invoke_before'\nactivesupport (5.2.6) lib/active_support/callbacks.rb:513:in `each'\nactivesupport (5.2.6) lib/active_support/callbacks.rb:513:in `invoke_before'\nactivesupport (5.2.6) lib/active_support/callbacks.rb:131:in `run_callbacks'\nactionpack (5.2.6) lib/abstract_controller/callbacks.rb:41:in `process_action'\nactionpack (5.2.6) lib/action_controller/metal/rescue.rb:22:in `process_action'\nactionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'\nactivesupport (5.2.6) lib/active_support/notifications.rb:168:in `block in instrument'\nactivesupport (5.2.6) lib/active_support/notifications/instrumenter.rb:23:in `instrument'\nactivesupport (5.2.6) lib/active_support/notifications.rb:168:in `instrument'\nactionpack (5.2.6) lib/action_controller/metal/instrumentation.rb:32:in `process_action'\nactionpack (5.2.6) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'\nactionpack (5.2.6) lib/abstract_controller/base.rb:134:in `process'\nactionview (5.2.6) lib/action_view/rendering.rb:32:in `process'\nactionpack (5.2.6) lib/action_controller/metal.rb:191:in `dispatch'\nactionpack (5.2.6) lib/action_controller/metal.rb:252:in `dispatch'\nactionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'\nactionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:34:in `serve'\nactionpack (5.2.6) lib/action_dispatch/journey/router.rb:52:in `block in serve'\nactionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `each'\nactionpack (5.2.6) lib/action_dispatch/journey/router.rb:35:in `serve'\nactionpack (5.2.6) lib/action_dispatch/routing/route_set.rb:840:in `call'\nrack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'\nrack (2.2.3) lib/rack/etag.rb:27:in `call'\nrack (2.2.3) lib/rack/conditional_get.rb:40:in `call'\nrack (2.2.3) lib/rack/head.rb:12:in `call'\nactionpack (5.2.6) lib/action_dispatch/http/content_security_policy.rb:18:in `call'\nrack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'\nrack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'\nactionpack (5.2.6) lib/action_dispatch/middleware/cookies.rb:670:in `call'\nactionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'\nactivesupport (5.2.6) lib/active_support/callbacks.rb:98:in `run_callbacks'\nactionpack (5.2.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'\nactionpack (5.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'\nactionpack (5.2.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'\nlograge (0.11.2) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'\nrailties (5.2.6) lib/rails/rack/logger.rb:26:in `block in call'\nactivesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `block in tagged'\nactivesupport (5.2.6) lib/active_support/tagged_logging.rb:28:in `tagged'\nactivesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `tagged'\nrailties (5.2.6) lib/rails/rack/logger.rb:26:in `call'\nactionpack (5.2.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'\nrequest_store (1.5.0) lib/request_store/middleware.rb:19:in `call'\nactionpack (5.2.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'\nrack (2.2.3) lib/rack/method_override.rb:24:in `call'\nrack (2.2.3) lib/rack/runtime.rb:22:in `call'\nactivesupport (5.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'\nactionpack (5.2.6) lib/action_dispatch/middleware/executor.rb:14:in `call'\nrack (2.2.3) lib/rack/sendfile.rb:110:in `call'\nrailties (5.2.6) lib/rails/engine.rb:524:in `call'\n/opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'\n/opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'\n/opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'\n/opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'\n/opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'"
```

Any idea what's causing this ?
I have this exact same installation with ondemand-1.8.20 and it's working fine.

**Comment by johrstrom** [comment]
Are you using a proxy? We enabled more secure CSRF options in 2.0. It works for us when we just use `servername` in `ood_portal.yml`, I'm wondering if there's some issue with `X-Forwarded-For` headers.

**Comment by GloktarFR** [comment]
I don't use a proxy, but it's a simple testing platform and I'm using SSH tunneling to redirect the ports and be able to connect to the portal from the browser. Also my `ood_portal.yml` doesn't contain a `servername` directive.

My SSH tunnel looks like this:
`ssh -N -L8080:localhost:80 <my-ood-server>`

In my browser, I'm using URL:
`http://localhost:8080`

**Comment by johrstrom** [comment]
Thanks. Yea there's something buggy here with `localhost`.  You can turn strict checking off, though I wouldn't advise it.

**Comment by GloktarFR** [comment]
I'm sorry, what parameter are you referring to ?

**Comment by johrstrom** [comment]
Sorry, it's a rails initializer that you'd have do add in `/etc/ood/apps/dashboard/initializers`.  What I tried off hand didn't work, so I'll have to keep looking into it.

**Comment by GloktarFR** [comment]
Alright I see.
Please let me know if I can be of any help with testing or anything else.

**Comment by johrstrom** [comment]
OK looks like we have a hard dependency on https in 2.0. Try as I might to find how to make this configurable the ordering of the initialzers just doesn't work (/etc initializers are always being executed first and overwritten by /var/www) 

`/var/www/ood/apps/sys/dashboard/config/initializers/session_store.rb` is the file you'll have to edit. Here I give you two options, you only need one. The first will just let you transmit session data over plain http.  The second uses files on the server to store session data so that you don't have to transmit them over the wire.

```ruby
# contents of /var/www/ood/apps/sys/dashboard/config/initializers/session_store.rb
# This is what it currently is, which doesn't work over plain http
#Rails.application.config.session_store :cookie_store, key: '_dashboard_session', secure: Rails.env.production?

# setting this to false means you can have this stored in a cookie - but your session data is 
# transmitted over plain http which is not very secure!
Rails.application.config.session_store :cookie_store, key: '_dashboard_session', secure: false

# This option may be a little more secure. Here I'm making a temp directory which should be 700 so other 
# folks can read these files. You could also use "#{ENV['HOME']/.ood-cache}" if you think a home directory would be better.
Rails.application.config.session_store :cache_store, { cache: ActiveSupport::Cache::FileStore.new(Dir.mktmpdir.to_s) }
```

**Comment by johrstrom** [comment]
Actually, you should just start using SSL on your apache instance. It's very easy to get let's encrypt certificates.

**Comment by GloktarFR** [comment]
It's working perfectly fine, thank you for the workaround.

I totally agree with you, SSL is quite easy to setup and I've already done that for production purpose.
But it's also true that I find it more convenient to test new versions of OOD using only one single virtual machine without worrying too much about the SSL layer.

Anyway, thank you again for all the help you provided.

**Comment by johrstrom** [comment]
Thanks for the ticket. I've created a couple follow up tickets based off of it.

I'm going to close this as a work around and anyone in the future should look at #1227 to allow for easier configuration of this, which we should be able to release in 2.0.11.

**Comment by johrstrom** [comment]
Since 2.0.16, the resolution in this comment stands. Sites should be able to drop an override file here.

`/etc/ood/config/apps/dashboard/config/initializers/session_store_override.rb`

https://github.com/OSC/ondemand/issues/1193#issuecomment-862659031

**Comment by qlux** [comment]
Just a note if someone ends up on this while testing the platform without ssl at the beginning, initializers has been moved to:
```
/etc/ood/config/apps/dashboard/initializers
```
and
```
/etc/ood/config/apps/myjobs/initializers/
```

**Comment by glennpj** [comment]
I am trying to evaluate OOD to see if I want to deploy it on my HPC system and I am seeing the invalid token issue with version 2.0.31. I have it set up on a test node using PAM auth and no SSL. The override workaround does not seem to have any effect. What is not currently working for me is
- file upload
- job composing
- interactive desktop

Here are examples of the errors.
```
App 119130 output: [2023-02-14 11:52:02 -0600 ]  INFO "method=GET path=/pun/sys/dashboard/files/fs/Users/gpjohnsn format=html controller=Fil
esController action=fs status=200 duration=32.03 view=16.58"
App 119130 output: [2023-02-14 11:52:05 -0600 ]  INFO "method=GET path=/pun/sys/dashboard/files/fs/Users/gpjohnsn format=html controller=Fil
esController action=fs status=200 duration=1558.55 view=435.99"
App 119130 output: [2023-02-14 11:52:22 -0600 ]  WARN "Can't verify CSRF token authenticity."
App 119130 output: [2023-02-14 11:52:22 -0600 ]  INFO "method=POST path=/pun/sys/dashboard/files/upload format=*/* controller=FilesControlle
r action=upload status=422 error='ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken' duration=1.51 view
=0.00"
App 119130 output: [2023-02-14 11:52:22 -0600 ] FATAL ""
App 119130 output: [2023-02-14 11:52:22 -0600 ] FATAL "ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToke
n):"
```
```
App 119130 output: [2023-02-14 11:52:29 -0600 ]  INFO "execve = [\"git\", \"describe\", \"--always\", \"--tags\"]"
App 119130 output: [2023-02-14 11:52:29 -0600 ]  INFO "method=GET path=/pun/sys/dashboard/batch_connect/sys/bc_desktop/argon_login/session_contexts/new format=html controller=BatchConnect::SessionContextsController action=new status=200 duration=55.52 view=33.50"
App 119130 output: [2023-02-14 11:52:31 -0600 ]  WARN "Can't verify CSRF token authenticity."
App 119130 output: [2023-02-14 11:52:31 -0600 ]  INFO "method=POST path=/pun/sys/dashboard/batch_connect/sys/bc_desktop/argon_login/session_contexts format=html controller=BatchConnect::SessionContextsController action=create status=422 error='ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken' duration=1.53 view=0.00"
App 119130 output: [2023-02-14 11:52:31 -0600 ] FATAL ""
App 119130 output: [2023-02-14 11:52:31 -0600 ] FATAL "ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):"
App 119130 output: [2023-02-14 11:52:31 -0600 ] FATAL ""
```

It seems like this is the same issue but perhaps something else has changed.

Thanks.

**Comment by johrstrom** [comment]
The example I gave has 2 items, maybe just use one?

```
# contents of /etc/ood/config/apps/dashboard/initializers/session_store.rb
Rails.application.config.session_store :cookie_store, key: '_dashboard_session', secure: false
```
and
```
# contents of /etc/ood/config/apps/myjobs/initializers/session_store.rb
Rails.application.config.session_store :cookie_store, key: '_myjobs_session', secure: false
```

**Comment by glennpj** [comment]
I was indeed just using one of the changes. I did eventually try both workarounds but only one at a time. Neither worked. I made sure to restart the server in between attempts, etc.

**Comment by glennpj** [comment]
I just discovered that if I modify the files in `/var/www/ood/apps/sys/`directly then things work. So it seems that the overrides are just not taking affect. I can work with the direct edits as I am just testing on a dev host.

**Comment by johrstrom** [comment]
Thanks for the update! I'm sorry, I'm on something else. Hope the evaluation turns out good!
