### ISSUE TITLE
safe render batch connect form items

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1349]
From discourse
https://discourse.osc.edu/t/debugging-matlab-app/1635/2

It's very hard to get a stack trace like below and know what it means. Of course maintainers may know off hand what this means/is, but the vast majority of admins/app developers would now know what's causing this. 

```text
#<ActionView::Template::Error: undefined method `map' for nil:NilClass>

/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.9/gems/actionview-5.2.6/lib/action_view/helpers/form_options_helper.rb:364:in `options_for_select'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.9/gems/actionview-5.2.6/lib/action_view/helpers/tags/select.rb:25:in `render'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.9/gems/actionview-5.2.6/lib/action_view/helpers/form_options_helper.rb:165:in `select'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.9/gems/actionview-5.2.6/lib/action_view/helpers/form_options_helper.rb:823:in `select'
... 
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.9/gems/bootstrap_form-4.5.0/lib/bootstrap_form/form_group_builder.rb:24:in `form_group_builder'
/opt/ood/ondemand/root/usr/share/gems/2.7/ondemand/2.0.9/gems/bootstrap_form-4.5.0/lib/bootstrap_form/inputs/select.rb:11:in `select_with_bootstrap'
/var/www/ood/apps/sys/dashboard/app/helpers/batch_connect/session_contexts_helper.rb:11:in `create_widget'
/var/www/ood/apps/sys/dashboard/app/views/batch_connect/session_contexts/_form.html.erb:3:in `block (2 levels) in _app_views_batch_connect_session_contexts__form_html_erb__1715347084576486627_54660'
/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session_context.rb:41:in `each'
/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session_context.rb:41:in `each'
```

So ... we should try to validate things like - select widgets have an array of options and if it doesn't turn it into a text field and bubble up an error (in plain language) about what's wrong. In this case, the YAML defining this select widget has no options.

**Comment by johrstrom** [comment]
I just happened to get this error, so I thought I'd document here.

I think we're looking for an experience a lot like this:

![image](https://user-images.githubusercontent.com/4874123/136845690-355b5553-18f2-42be-824f-2d81b90f7b3f.png)
