### ISSUE TITLE
upgrade ood-portal-generator rspec to 3.10.0

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1559]
ood-portal-generator tests fail when you run `rake spec` with the error below. Running `bundle exec rake spec` fixes the issue because it's on 3.9.0 and the main gemfile (which throws this error) is 3.10.0

```text
  2) OodPortalGenerator::Application checksum_matches? matches
     Failure/Error: Digest::SHA256.hexdigest(read_file_omitting_comments(input))
     
     NameError:
       uninitialized constant RSpec::Support::Differ
     # ./lib/ood_portal_generator/application.rb:105:in `checksum'
     # ./lib/ood_portal_generator/application.rb:117:in `checksum_matches?'
     # ./spec/application_spec.rb:407:in `block (3 levels) in <top (required)>'
```

I'm sure there's a ticket for this - but the ood-portal-generator's lockfile (along with nginx stage's) need to be updated in the main `rake update` task.

**Comment by johrstrom** [comment]
I can't as of now replicate this, but the ticket to update these gems is #691.
