### ISSUE TITLE
superclass mismatch for class InvalidManifest

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1868]
I don't know why this is happening, but we're running into this stack trace on various pages (I just got it on 
`BatchConnect::SessionsController#index`). 

```
    app/apps/manifest.rb:189:in `<top (required)>'
    zeitwerk (2.5.4) lib/zeitwerk/kernel.rb:27:in `require'
    zeitwerk (2.5.4) lib/zeitwerk/kernel.rb:27:in `require'
    app/apps/ood_app.rb:198:in `manifest'
    app/apps/ood_app.rb:25:in `manifest?'
    app/apps/ood_app.rb:33:in `should_appear_in_nav?'
    app/controllers/application_controller.rb:40:in `select'
```

Don't know what's going on or why we'd get this error, could possibly be due to #1842, the updates from last week? I started to see it last week anyhow, so that's my best guess.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201901893785535) by [Unito](https://www.unito.io)

**Comment by johrstrom** [comment]
Note that it's only happening in dev. It doesn't actually affect the production dashboard (i.e., nightlies).
