### ISSUE TITLE
Shell app does not filter unreadable clusters

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#1950]
Shell app does not filter unreadable cluster files when it should. Here's the error we're seeing right now with ascend placed behind FACLs.

```
App 99737 output: Error: EACCES: permission denied, open '/etc/ood/config/clusters.d/ascend.yml'
App 99737 output:     at Object.openSync (fs.js:462:3)
App 99737 output:     at Object.readFileSync (fs.js:364:35)
App 99737 output:     at /var/www/ood/apps/sys/shell/app.js:83:32
App 99737 output:     at Array.map (<anonymous>)
App 99737 output:     at Object.<anonymous> (/var/www/ood/apps/sys/shell/app.js:83:4)
App 99737 output:     at Module._compile (internal/modules/cjs/loader.js:999:30)
App 99737 output:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
App 99737 output:     at Module.load (internal/modules/cjs/loader.js:863:32)
App 99737 output:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
App 99737 output:     at Module.require (internal/modules/cjs/loader.js:887:19) {
App 99737 output:   errno: -13,
App 99737 output:   syscall: 'open',
App 99737 output:   code: 'EACCES',
App 99737 output:   path: '/etc/ood/config/clusters.d/ascend.yml'
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202116797801191) by [Unito](https://www.unito.io)

**Comment by lukew3** [comment]
I'm not able to reproduce this error. Any ideas why?

**Comment by johrstrom** [comment]
You have a cluster.d folder somewhere in your home right?

put this into a `~/ondemand/dev/shell/.env.local`
```
OOD_CLUSTERS=/whereever/your/cluster.d/directory is.
```

Then `chmod 000`  on one of them so it's unreadable by you.
