### ISSUE TITLE
nginx_stage has issues with Ubuntu-22.04 and possibly Ruby 3.0

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand#2049]
```
root@ubuntu2204:/# /opt/ood/nginx_stage/sbin/nginx_stage pun -u ood
wrong number of arguments (given 1, expected 0; required keywords: env, owner, name)
Run 'nginx_stage --help' to see a full list of available command line options.
```

Likely issues with method argument handling changes in Ruby 3.0.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202339759100342) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
Here is full back trace after modifying nginx_stage code a little:

```
/opt/ood/nginx_stage/lib/nginx_stage/configuration.rb:245:in `app_config_path'
	/opt/ood/nginx_stage/lib/nginx_stage/views/pun_config_view.rb:110:in `block in app_configs'
	/opt/ood/nginx_stage/lib/nginx_stage/views/pun_config_view.rb:109:in `map'
	/opt/ood/nginx_stage/lib/nginx_stage/views/pun_config_view.rb:109:in `app_configs'
	(erb):119:in `render'
	/usr/lib/ruby/3.0.0/erb.rb:905:in `eval'
	/usr/lib/ruby/3.0.0/erb.rb:905:in `result'
	/opt/ood/nginx_stage/lib/nginx_stage/generator.rb:136:in `render'
	/opt/ood/nginx_stage/lib/nginx_stage/generator.rb:103:in `template'
	/opt/ood/nginx_stage/lib/nginx_stage/generators/pun_config_generator.rb:110:in `block in <class:PunConfigGenerator>'
	/opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `instance_eval'
	/opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `block in invoke'
	/opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `each'
	/opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `invoke'
	/opt/ood/nginx_stage/lib/nginx_stage/application.rb:41:in `start'
	-e:1:in `<main>'
```
