### ISSUE TITLE
Rails secret base key issue on Ruby 3.0 / Ubuntu 22.04

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand#2050]
App 4333 output: [ 2022-05-25 12:49:18.7471 4333/0x00005570652d16f0(Worker 1) utils.rb ]: *** Exception ArgumentError in Rack application object (`secret_key_base` for production environment must be a type of String`) (process 4333, thread 0x00005570652d16f0(Worker 1)):
 App 4333 output: 	from /opt/ood/gems/gems/railties-6.1.5.1/lib/rails/application.rb:601:in `validate_secret_key_base'
 App 4333 output: 	from /opt/ood/gems/gems/railties-6.1.5.1/lib/rails/application.rb:437:in `secret_key_base'
 App 4333 output: 	from /opt/ood/gems/gems/railties-6.1.5.1/lib/rails/application.rb:273:in `env_config'
 App 4333 output: 	from /opt/ood/gems/gems/railties-6.1.5.1/lib/rails/engine.rb:722:in `build_request'
 App 4333 output: 	from /opt/ood/gems/gems/railties-6.1.5.1/lib/rails/application.rb:625:in `build_request'
 App 4333 output: 	from /opt/ood/gems/gems/railties-6.1.5.1/lib/rails/engine.rb:538:in `call'
 App 4333 output: 	from /opt/ood/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
 App 4333 output: 	from /opt/ood/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
 App 4333 output: 	from /opt/ood/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
 App 4333 output: 	from /opt/ood/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
 App 4333 output: 	from /opt/ood/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
 [ W 2022-05-25 12:49:18.7473 3016/T8 age/Cor/Con/InternalUtils.cpp:96 ]: [Client 1-2] Sending 502 response: application did not send a complete response

Not sure if this means we need to generate and ship packages with the secret_key_base defined?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202339864120080) by [Unito](https://www.unito.io)

**Comment by treydock** [comment]
@johrstrom Not quite sure if this is bug with Ruby 3.0 somewhere in Dashboard, like default not getting set?  Not sure how didn't run into this issue with other OSes using the updated Rails app unless this is just some issue specific to Ruby 3.0.

**Comment by treydock** [comment]
I didn't think to look in nginx_stage but you're right. The file exists but it's empty:

```
root@ubuntu2204:/# ls -la /var/lib/ondemand-nginx/config/puns/ood.secret_key_base.txt 
-rw-r--r-- 1 root root 0 May 25 12:28 /var/lib/ondemand-nginx/config/puns/ood.secret_key_base.txt
root@ubuntu2204:/# cat /var/lib/ondemand-nginx/config/puns/ood.secret_key_base.txt 
root@ubuntu2204:/# 
```

Once I remove the file and run again I get this:

```
Failed to write secret to path: /var/lib/ondemand-nginx/config/puns/ood.secret_key_base.txt
no implicit conversion of Hash into Integer
/opt/ood/nginx_stage/lib/nginx_stage/secret_key_base_file.rb:26:in `write'
/opt/ood/nginx_stage/lib/nginx_stage/secret_key_base_file.rb:26:in `generate'
/opt/ood/nginx_stage/lib/nginx_stage/generators/pun_config_generator.rb:99:in `block in <class:PunConfigGenerator>'
/opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `instance_eval'
/opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `block in invoke'
/opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `each'
/opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `invoke'
/opt/ood/nginx_stage/lib/nginx_stage/application.rb:41:in `start'
-e:1:in `<main>'
/opt/ood/nginx_stage/lib/nginx_stage/secret_key_base_file.rb:26:in `write': no implicit conversion of Hash into Integer (TypeError)
	from /opt/ood/nginx_stage/lib/nginx_stage/secret_key_base_file.rb:26:in `generate'
	from /opt/ood/nginx_stage/lib/nginx_stage/generators/pun_config_generator.rb:99:in `block in <class:PunConfigGenerator>'
	from /opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `instance_eval'
	from /opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `block in invoke'
	from /opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `each'
	from /opt/ood/nginx_stage/lib/nginx_stage/generator.rb:93:in `invoke'
	from /opt/ood/nginx_stage/lib/nginx_stage/application.rb:41:in `start'
	from -e:1:in `<main>'
```
