### ISSUE TITLE
Dashboard: Processing erb on each request to generate the description information produces performance issues

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#210]
Note: this should be introduced under a feature flag that disables the new behavior by default. That way it can be released in the patch release and be optionally enabled by interested sites. The default can change in a later release.

#### Updated April 26, 2021
The logic currently is to:

* render form.yml.erb (or load form.yml), and use title and description as provided, otherwise defaulting to the manifest

With this issue the new logic would be:

* for nav, always use the default from the manifest (or the titelized form of the app name if a manifest is not present)
* for the desktop apps or other subapps, a new manifest location would be added - next to the form.yml so /etc/ood/config/apps/bc_desktop/owens.yml.erb would use /etc/ood/config/apps/bc_desktop/owens.manifest.yml
* the filtering out of apps by "valid?" checks from the nav bar would be omitted

The technical design for this is as follows:

* add factory method and move the loading and rendering of the form.yml to this method and pass the resulting form config hash as an argument; will want to support passing in validation_reason errors as well
* add second factory method that passes in an empty hash and use this when working with the app object for navigation
* omit the calls to valid? on batch connect apps in OodApp class

With a configuration option we could switch it back to the previous functionality. We could also wait until someone complains that the previous functionality is necessary and worth the performance cost before adding back this support.

**NOTE: before doing this, sub_app_list must be refactored out of all the places it is used and the knowledge of that relationship should only be in one place - the router that creates the OodApp objects. Then the new functionality will need to only create OodApp objects for those "apps" that have a manifest.yml (or subapp.manifest.yml). This is how we address the bug where currently a sub_app_list pulls in any yml/yml.erb as a subapp, and only after validating the rendered erb does it determine it is not (such as submit.yml.erb in /etc).**

#### Old description
We load and process the batch connect form.yml.erb files to generate the title and description of the iHPC apps. Unfortunately, this means that any expensive parts of the form.yml.erb are also executed. If there is code to build a queue list from a command, for example, that will be executed for each iHPC app on every request to the dashboard. This is terrible for performance.

**Comment by ericfranz** [comment]
Maybe the solution for backwards compatibility in some form is to support a `manifest.yml.erb`.

**Comment by andrejcermak** [comment]
Hi, I tried the solution presented in the merged pull request, but IMO it solves the issue only partially. Some of our interactive applications have form.yml.erb with some code that builds the form and this code is called when
- you reload the page
- when you go to other ood page
- when you open other interactive apps
- when interactive app is launched and the info function is called periodically 
Moreover, lets say we have app A and app B, then even when app A is being launched, both app A and B's form is still rendered.

**Comment by johrstrom** [comment]
OK, I can reopen and take a look again.

**Comment by andrejcermak** [comment]
Thank you. After further inspection i found that the above mentioned issues are solved by Commit a13d50a. The only apps that are still being rendered are subset of the batch connect apps, but I am not sure what they have in common. I will post part of the call stack so you could decipher it from there:


["/var/www/ood/apps/sys/dashboard/app/models/batch_connect/app.rb:40:in `new'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/app.rb:40:in `from_token'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:89:in `app'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:612:in `app_ssh_to_compute_node'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:599:in `app_override_ssh_to_compute_node?'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:590:in `override_global_ssh_to_compute_node?'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:581:in `ssh_to_compute_node?'", "/var/www/ood/apps/sys/dashboard/app/views/batch_connect/sessions/card/_host.html.erb:2:in `_app_views_batch_connect_sessions_card__host_html_erb___3385876511548224716_21740'",

**Comment by johrstrom** [comment]
Thanks for the stack trace. I see it's `from_token` where it's not being cached.

**Comment by andrejcermak** [comment]
Is it possible to have it cached there as well?

**Comment by andrejcermak** [comment]
After digging deeper i found that `from_token` is called once per active interactive session periodically. 

The major issue is with
"/var/www/ood/apps/sys/dashboard/app/models/batch_connect/app.rb:441:in `form_config'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/app.rb:51:in `initialize'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/app.rb:391:in `new'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/app.rb:391:in `block in build_sub_app_list'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/app.rb:387:in `map'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/app.rb:387:in `build_sub_app_list'", "/var/www/ood/apps/sys/dashboard/app/models/batch_connect/app.rb:338:in `sub_app_list'", "/var/www/ood/apps/sys/dashboard/app/apps/ood_app.rb:142:in `links'", "/var/www/ood/apps/sys/dashboard/app/apps/nav_bar.rb:143:in `block in extract_links'", "/var/www/ood/apps/sys/dashboard/app/apps/nav_bar.rb:142:in `map'", "/var/www/ood/apps/sys/dashboard/app/apps/nav_bar.rb:142:in `extract_links'", "/var/www/ood/apps/sys/dashboard/app/apps/nav_bar.rb:136:in `item_from_token'", "/var/www/ood/apps/sys/dashboard/app/apps/nav_bar.rb:8:in `block in items'", "/var/www/ood/apps/sys/dashboard/app/apps/nav_bar.rb:6:in `map'", "/var/www/ood/apps/sys/dashboard/app/apps/nav_bar.rb:6:in `items'", "/var/www/ood/apps/sys/dashboard/app/controllers/application_controller.rb:27:in `set_custom_navigation'",

as it is called on every user action in the UI multiple times.  
I guess could be solved by caching in the `links` function.

**Comment by johrstrom** [comment]
I don't know if I'll be able to refactor `BatchConnect::App#from_token` in time for 4.1. The issue I'm having is with sub apps and how those objects are initialized through their parent application. Routers (where this is being cached) don't create subapps. Maybe they do when the links are being built, but the subapps token is different from the parent's token.

In any case, it's difficult to do cleanly, so I'm going to have to defer it for a bit and pick up lower hanging fruit for 4.1.

**Comment by johrstrom** [comment]
I'm going to close this as done as I feel it is.

This ticket notes that we're processing ERB "on each request". This is no longer the case. While I've just created #4870 to take care of `BatchConnect::App#from_token` the last spot where we're still processing ERB for those pages, but these are limited.

In any case, we don't process ERB "on each request" anymore so we've at least made progress in this regard. We do still however process ERB "on specific requests", but that's captured in #4870
