### ISSUE TITLE
issues trying to build rpm locally

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand#2355]
I'm trying to test the e2e tests for centos7 and am failing to build the RPM.  Not sure how why works in the CI (I'm using the same environment variables).

I can see in `docker.io/ohiosupercomputer/ood-buildbox-el7:0.5.0` `~/.rpmmacros` exists, but `~/.gnupg` does not.

```
== Bootstrap RPM ==
        Bootstrap /root
cp: cannot stat ‘/home/ood/.gnupg’: No such file or directory
rake aborted!
Command failed with status (1): [cp -r /home/ood/.rpmmacros /home/ood/.gnup...]
/ondemand-packaging/gems/gems/ood_packaging-0.5.0/lib/ood_packaging/build.rb:169:in `bootstrap_rpm!'
/ondemand-packaging/gems/gems/ood_packaging-0.5.0/lib/ood_packaging/build.rb:143:in `run!'
/ondemand-packaging/gems/gems/ood_packaging-0.5.0/lib/ood_packaging/tasks.rb:47:in `block (3 levels) in <top (required)>'
/ondemand-packaging/gems/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/ondemand-packaging/rake:23:in `load'
/ondemand-packaging/rake:23:in `<main>'
Tasks: TOP => ood_packaging:package:build
```

**Comment by johrstrom** [comment]
I see that it's in a podman_runtime? if block and so that's why it's different than the CI --- I'll move this issue to that repo.

https://github.com/OSC/ondemand-packaging/blob/ca1580d9a1c81ab20a8512e25cf873958d28df5d/lib/ood_packaging/build.rb#L167-L171
