### ISSUE TITLE
DEVELOPMENT.md directions do not work

### ISSUE THREAD

**Issue by Oglopf** [OSC/ondemand#2431]
The instructions as listed lead to an error:

    git clone https://github.com/OSC/ondemand.git ~/ondemand/src
    cd ~/ondemand/src
    rake dev:start
    rake aborted!
    LoadError: cannot load such file -- dotenv
    <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
    <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
    /home/trav/ondemand/src/lib/tasks/rake_helper.rb:4:in `<top (required)>'
    <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
    <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
    /home/trav/ondemand/src/Rakefile:13:in `<top (required)>'
    /usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
    (See full trace by running task with --trace)To get things to run correctly I've had to do the following:

```
git clone https://github.com/OSC/ondemand.git ~/ondemand/src
cd ~/ondemand/src
mkdir .bundle
vim .bundle/config
```

Then adding an entry to ensure my `vendor/bundle` path is used:

## ```
BUNDLE_PATH: vendor/bundle

    Now getting the `Gems` that seem to be needed:bundle install

    After this running `bundle exec` to ensure those local `gems` are used works:bundle exec rake dev:start
```

I'm trying to understand if I'm building this wrong, or if there is something I'm missing about how all this works and should be done. Why did the simple `rake dev:start` not work?



┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203550075137288) by [Unito](https://www.unito.io)

**Comment by gerald-byrket** [comment]
@Oglopf   

I'll see if i can duplicate tomorrow.

-gerald

**Comment by Oglopf** [comment]
Even with this running, I get errors trying to do any work in the container as it seems like I'm missing `Gems` when trying to build apps within it.

For instance, if you now want to go work on the dashboard, you then connect this up as a `dev` app by doing the usual...cumbersome  setup of running `bundle exec rake dev:exec` then `su <user>` then `cd ondemand/dev` then `ln -s ../src/apps/dashboard/ dashboard` then `bin/setup` but at this step I get errors around:
```
An error occurred while installing stringio (3.0.2), and Bundler cannot continue.

In Gemfile:
  sdoc was resolved to 2.4.0, which depends on
    rdoc was resolved to 6.4.0, which depends on
      psych was resolved to 4.0.6, which depends on
        stringio
/usr/share/gems/gems/rake-13.0.6/lib/rake/file_utils.rb:67:in `block in create_shell_runner': Command failed with status (5): [bin/bundle check 1>/dev/null 2>&1 || bin/b...] (RuntimeError)
	from /usr/share/gems/gems/rake-13.0.6/lib/rake/file_utils.rb:57:in `sh'
	from bin/setup:59:in `block in <main>'
	from /usr/share/ruby/fileutils.rb:139:in `chdir'
	from /usr/share/ruby/fileutils.rb:139:in `cd'
	from /usr/share/gems/gems/rake-13.0.6/lib/rake/file_utils_ext.rb:35:in `chdir'
	from bin/setup:50:in `<main>'
```
And at this point I'm at a total loss as to where what `gems` were installed locally or here in this container. Worse still, if you have a version mismatch of the `ruby` version you are in huge trouble, unless you go through the hassle of using `rbenv` or `rvm` both of which are broke on certain distributions, and we provide _no_ indication of.

I have never used a container flow like this, so I think I need some lessons on how this should work. For myself, I typically just make code changes and rebuild my container, but with OOD we are doing an image pull that is locked down, then doing dev work in OOD in the container, and I can't seem to get the thing to do much beyond loading config files for me.

**Comment by gerald-byrket** [comment]
@Oglopf 

definitely problem

**Comment by Oglopf** [comment]
I'm closing this out as it seems like it works as expected per Trey's comments

**Comment by Oglopf** [comment]
The container does not run using the instructions on ubunt 22. You must use `bundle exec rake dev:start` and even then, I can't seem to hit the web interface though login and mounts work fine.

**Comment by Oglopf** [comment]
Also, why do we only have an image for Rocky 8 to do this?

**Comment by johrstrom** [comment]
> Also, why do we only have an image for Rocky 8 to do this?

Do you want a different OS?
