### ISSUE TITLE
Release 1.7.1 Broke OnDemand Test

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ondemand#299]
Ever since the 1.7.1 release I have not been able to use our test instance. I see the following error in the Nginx log:

```
webtest02:dashboard mrodgers$ read_logs 
App 1867 output:     /opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
App 1867 output:     /opt/rh/rh-ruby25/root/usr/share/gems/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
App 1867 output:     /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
App 1867 output:     /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
App 1867 output:     /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:363:in `activate_gem'
App 1867 output:     /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:221:in `block in run_load_path_setup_code'
App 1867 output:     /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:527:in `running_bundler'
App 1867 output:     /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:220:in `run_load_path_setup_code'
App 1867 output:     /opt/rh/ondemand/root/usr/share/passenger/helper-scripts/rack-loader.rb:86:in `load_app'
App 1867 output:     /opt/rh/ondemand/root/usr/share/passenger/helper-scripts/rack-loader.rb:116:in `block in <module:App>'
App 1867 output:     /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
App 1867 output:     /opt/rh/ondemand/root/usr/share/passenger/helper-scripts/rack-loader.rb:115:in `<module:App>'
App 1867 output:     /opt/rh/ondemand/root/usr/share/passenger/helper-scripts/rack-loader.rb:28:in `<module:PhusionPassenger>'
App 1867 output:     /opt/rh/ondemand/root/usr/share/passenger/helper-scripts/rack-loader.rb:27:in `<main>'
[ E 2019-11-13 12:48:22.3370 1842/Tj age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/www/ood/apps/sys/dashboard: The application encountered the following error: Could not find rake-13.0.0 in any of the sources (Bundler::GemNotFound)
```

What is odd about this is that I have seen that @ericfranz can still access the Dashboard without trouble.

**Comment by MorganRodgers** [comment]
The original fix for this problem was upgrading the ondemand-runtime Gem to version 1.7-5, which I've confirmed is installed on test.

**Comment by MorganRodgers** [comment]
My `GEM_PATH` when the ondemand SCL is loaded:

```
webtest02:~ mrodgers$ scl enable ondemand -- ruby <<< 'p ENV["GEM_PATH"]'
"/opt/ood/ondemand/root/usr/share/gems/2.5:/opt/ood/ondemand/root/usr/share/gems/2.5/ondemand/1.7.1:/opt/ood/ondemand/root/usr/share/gems/2.5/apps/*:"
```

**Comment by treydock** [comment]
I can access test instance without issue.

The gem that your session says is missing is present:
```
[root@webtest02 ~]# scl enable ondemand -- gem list rake

*** LOCAL GEMS ***

rake (13.0.0, 12.3.3, 12.3.0)
```

Passenger dumps a lot of information to HTML file and I see this in `envvars`:

```
GEM_PATH=/opt/ood/ondemand/root/usr/share/gems/2.5:/opt/ood/ondemand/root/usr/share/gems/2.5/ondemand/1.7.1:/opt/ood/ondemand/root/usr/share/gems/2.5/apps/*:
```

The last path maybe wrong but the `1.7.1` path is one with rake 13.0.0.

**Comment by MorganRodgers** [comment]
The 1.7.1 Dashboard crashes for Kinan as well.

**Comment by treydock** [comment]
I think something is spilling into the environment or some other Gemfile is being looked at. For Kinan I see this:

```
App 8767 output: Ignoring nokogiri-1.10.3 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.3
```

nokogiri 1.10.3 is not installed nor specified in dashboard Gemfile.lock. 

As a test, move ~/ondemand/dev to ~/ondemand/dev.bak, then restart your PUN and try again.

I'm guessing somewhere is a `.bundle/config` that has `BUNDLE_PATH` set and that's breaking things.

For Kinan:

```
# grep -HnR "nokogiri" /users/PZS0715/kalattar/ondemand/dev/*/Gemfile.lock
/users/PZS0715/kalattar/ondemand/dev/ood-activejobs/Gemfile.lock:88:      nokogiri (>= 1.5.9)
/users/PZS0715/kalattar/ondemand/dev/ood-activejobs/Gemfile.lock:95:    nokogiri (1.9.1)
/users/PZS0715/kalattar/ondemand/dev/ood-activejobs/Gemfile.lock:128:      nokogiri (~> 1.6)
/users/PZS0715/kalattar/ondemand/dev/quincy_rails/Gemfile.lock:84:      nokogiri (>= 1.5.9)
/users/PZS0715/kalattar/ondemand/dev/quincy_rails/Gemfile.lock:91:    nokogiri (1.10.3)
/users/PZS0715/kalattar/ondemand/dev/quincy_rails/Gemfile.lock:124:      nokogiri (~> 1.6)
```

I see nokogiri 1.10.3 which isn't part of ondemand core's Gemfile.lock

**Comment by MorganRodgers** [comment]
Eric and I just found what is breaking things for me: `~/.bundle/config`. By renaming that file we were able to unbreak things for me.

We should look into if there is a way to launch the process with Bundler ignoring the user's configuration files.

**Comment by treydock** [comment]
https://bundler.io/man/bundle-config.1.html

Could set `BUNDLE_USER_HOME` to `/dev/null` (at bottom of link above) or maybe different environment variable.

**Comment by treydock** [comment]
Maybe also set `BUNDLE_USER_CONFIG` to `/dev/null`

**Comment by MorganRodgers** [comment]
My problem is now understood; we should prevent other folks from having this problem: https://github.com/OSC/ondemand/issues/302.
