### ISSUE TITLE
Jobs are not expanding in activejobs

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand#323]
When I click the arrow to expand job details for OnDemand dev and test I get nothing:

<img width="1226" alt="Screen Shot 2019-11-26 at 12 26 10 PM" src="https://user-images.githubusercontent.com/739622/69661464-16892d80-1048-11ea-9884-95b390a40825.png">

When I do this on OnDemand production I get details:

<img width="1212" alt="Screen Shot 2019-11-26 at 12 26 16 PM" src="https://user-images.githubusercontent.com/739622/69661471-1ab54b00-1048-11ea-8266-c475be52c5b7.png">

**Comment by treydock** [comment]
This is what I see in console in Chrome:

```
VM538:1 GET https://ondemand-dev.osc.edu/pun/sys/activejobs/json?pbsid=8559720.owens-batch.ten.osc.edu&cluster=owens 500 (Internal Server Error)
(anonymous) @ VM538:1
send @ application-830605fbb6fff3b0d07c8c7280992f9cf65093ff6c5a50a227660c45f69ac8b9.js:3
ajax @ application-830605fbb6fff3b0d07c8c7280992f9cf65093ff6c5a50a227660c45f69ac8b9.js:3
s.ajax @ application-830605fbb6fff3b0d07c8c7280992f9cf65093ff6c5a50a227660c45f69ac8b9.js:3
Ce.<computed> @ application-830605fbb6fff3b0d07c8c7280992f9cf65093ff6c5a50a227660c45f69ac8b9.js:3
getJSON @ application-830605fbb6fff3b0d07c8c7280992f9cf65093ff6c5a50a227660c45f69ac8b9.js:3
(anonymous) @ application-830605fbb6fff3b0d07c8c7280992f9cf65093ff6c5a50a227660c45f69ac8b9.js:1
dispatch @ application-830605fbb6fff3b0d07c8c7280992f9cf65093ff6c5a50a227660c45f69ac8b9.js:2
m.handle @ application-830605fbb6fff3b0d07c8c7280992f9cf65093ff6c5a50a227660c45f69ac8b9.js:2
```

**Comment by treydock** [comment]
This is my PUN log:

```
App 23038 output: [2019-11-26 13:39:23 -0500 ]  INFO "method=GET path=/pun/sys/activejobs/json format=json controller=JobsController action=json status=500 error='ActionView::Template::Error: wrong number of arguments (given 1, expected 2..4)' duration=18.08 view=0.00"
App 23038 output: [2019-11-26 13:39:23 -0500 ] FATAL "ActionView::Template::Error (wrong number of arguments (given 1, expected 2..4)):\n    47:       <% end %>\n    48:       <div class=\"col-md-12\">\n    49:         <% if ENV[\"USER\"] == data.username %>\n    50:             <%= link_to \"\#{icon(\"folder-open\")} Open in File Manager\".html_safe, data.file_explorer_url, :class => \"btn btn-default\", :target => \"_blank\", :style => \"margin: 10px;\" if data.file_explorer_url %>\n    51:             <%= link_to \"\#{icon(\"terminal\")} Open in Terminal\".html_safe, data.shell_url, :class => \"btn btn-default\", :target => \"_blank\", :style => \"margin: 10px;\" if data.shell_url %>\n    52:             <%= link_to \"\#{icon(\"trash-o\")} Delete\".html_safe, delete_job_path(pbsid: data.pbsid, cluster: data.cluster), :class => \"btn btn-danger pull-right\", :style => \"margin: 10px;\", data: { method: \"delete\", confirm: \"Are you sure you want to delete \#{data.pbsid}\" } %>\n    53:         <% end %>\n  app/views/jobs/_extended_panel.html.erb:50:in `_app_views_jobs__extended_panel_html_erb__596270422006771024_23373240'\n  app/views/jobs/extended_data.json.jbuilder:1:in `_app_views_jobs_extended_data_json_jbuilder__584947234699671085_23699400'\n  app/controllers/jobs_controller.rb:31:in `block (2 levels) in json'\n  app/controllers/jobs_controller.rb:24:in `json'"
App 23038 output: [2019-11-26 13:40:23 -0500 ]  INFO "method=GET path=/pun/sys/activejobs/json format=json controller=JobsController action=json status=500 error='ActionView::Template::Error: wrong number of arguments (given 1, expected 2..4)' duration=13.75 view=0.00"
App 23038 output: [2019-11-26 13:40:23 -0500 ] FATAL "ActionView::Template::Error (wrong number of arguments (given 1, expected 2..4)):\n    47:       <% end %>\n    48:       <div class=\"col-md-12\">\n    49:         <% if ENV[\"USER\"] == data.username %>\n    50:             <%= link_to \"\#{icon(\"folder-open\")} Open in File Manager\".html_safe, data.file_explorer_url, :class => \"btn btn-default\", :target => \"_blank\", :style => \"margin: 10px;\" if data.file_explorer_url %>\n    51:             <%= link_to \"\#{icon(\"terminal\")} Open in Terminal\".html_safe, data.shell_url, :class => \"btn btn-default\", :target => \"_blank\", :style => \"margin: 10px;\" if data.shell_url %>\n    52:             <%= link_to \"\#{icon(\"trash-o\")} Delete\".html_safe, delete_job_path(pbsid: data.pbsid, cluster: data.cluster), :class => \"btn btn-danger pull-right\", :style => \"margin: 10px;\", data: { method: \"delete\", confirm: \"Are you sure you want to delete \#{data.pbsid}\" } %>\n    53:         <% end %>\n  app/views/jobs/_extended_panel.html.erb:50:in `_app_views_jobs__extended_panel_html_erb__596270422006771024_23373240'\n  app/views/jobs/extended_data.json.jbuilder:1:in `_app_views_jobs_extended_data_json_jbuilder__584947234699671085_23699400'\n  app/controllers/jobs_controller.rb:31:in `block (2 levels) in json'\n  app/controllers/jobs_controller.rb:24:in `json'"
```

**Comment by treydock** [comment]
Fixed newlines:

```
App 23038 output: [2019-11-26 13:40:23 -0500 ] FATAL "ActionView::Template::Error (wrong number of arguments (given 1, expected 2..4)):
    47:       <% end %>
    48:       <div class=\"col-md-12\">
    49:         <% if ENV[\"USER\"] == data.username %>
    50:             <%= link_to \"\#{icon(\"folder-open\")} Open in File Manager\".html_safe, data.file_explorer_url, :class => \"btn btn-default\", :target => \"_blank\", :style => \"margin: 10px;\" if data.file_explorer_url %>
    51:             <%= link_to \"\#{icon(\"terminal\")} Open in Terminal\".html_safe, data.shell_url, :class => \"btn btn-default\", :target => \"_blank\", :style => \"margin: 10px;\" if data.shell_url %>
    52:             <%= link_to \"\#{icon(\"trash-o\")} Delete\".html_safe, delete_job_path(pbsid: data.pbsid, cluster: data.cluster), :class => \"btn btn-danger pull-right\", :style => \"margin: 10px;\", data: { method: \"delete\", confirm: \"Are you sure you want to delete \#{data.pbsid}\" } %>
    53:         <% end %>
  app/views/jobs/_extended_panel.html.erb:50:in `_app_views_jobs__extended_panel_html_erb__596270422006771024_23373240'
  app/views/jobs/extended_data.json.jbuilder:1:in `_app_views_jobs_extended_data_json_jbuilder__584947234699671085_23699400'
  app/controllers/jobs_controller.rb:31:in `block (2 levels) in json'
  app/controllers/jobs_controller.rb:24:in `json'"
```

**Comment by treydock** [comment]
The problem is `icon` needs at least 2 arguments and likely a side effect of updating font-awesome gem
