### ISSUE TITLE
Activejobs: Unable to show extended job detail panels

### ISSUE THREAD

**Issue by AriettaZ** [OSC/ondemand#328]
After clicking the arrow icon, the extended panels of my active jobs failed to load. However, I'm able to see the details panel of the jobs submitted by others. This error is only in ondemand-test and ondemand-dev. Morgan was able to reproduce this error. 

![job details](https://user-images.githubusercontent.com/22674713/69977396-b6d3cc00-14f8-11ea-86e9-96a34bce6f7a.JPG)

```
#From my error.log
App 94347 output: [2019-12-02 10:37:45 -0500 ]  INFO "method=GET path=/pun/sys/activejobs/ format=html controller=JobsController action=index status=200 duration=3.43 view=3.09"
App 94347 output: [2019-12-02 10:37:46 -0500 ]  INFO "method=GET path=/pun/sys/activejobs/jobs.json format=json controller=JobsController action=index status=200 duration=9.79 view=0.00"
App 94347 output: [2019-12-02 10:37:47 -0500 ]  INFO "method=GET path=/pun/sys/activejobs/json format=json controller=JobsController action=json status=500 error='ActionView::Template::Error: wrong number of arguments (given 1, expected 2..4)' duration=7.84 view=0.00"
App 94347 output: [2019-12-02 10:37:47 -0500 ] FATAL "ActionView::Template::Error (wrong number of arguments (given 1, expected 2..4)):\n    47:       <% end %>\n    48:       <div class=\"col-md-12\">\n    49:         <% if ENV[\"USER\"] == data.username %>\n    50:             <%= link_to \"\#{icon(\"folder-open\")} Open in File Manager\".html_safe, data.file_explorer_url, :class => \"btn btn-default\", :target => \"_blank\", :style => \"margin: 10px;\" if data.file_explorer_url %>\n    51:             <%= link_to \"\#{icon(\"terminal\")} Open in Terminal\".html_safe, data.shell_url, :class => \"btn btn-default\", :target => \"_blank\", :style => \"margin: 10px;\" if data.shell_url %>\n    52:             <%= link_to \"\#{icon(\"trash-o\")} Delete\".html_safe, delete_job_path(pbsid: data.pbsid, cluster: data.cluster), :class => \"btn btn-danger pull-right\", :style => \"margin: 10px;\", data: { method: \"delete\", confirm: \"Are you sure you want to delete \#{data.pbsid}\" } %>\n    53:         <% end %>\n  app/views/jobs/_extended_panel.html.erb:50:in `_app_views_jobs__extended_panel_html_erb__1988449189020363592_25940760'\n  app/views/jobs/extended_data.json.jbuilder:1:in `_app_views_jobs_extended_data_json_jbuilder___3750275270075764802_26074340'\n  app/controllers/jobs_controller.rb:31:in `block (2 levels) in json'\n  app/controllers/jobs_controller.rb:24:in `json'"
```

**Comment by treydock** [comment]
This was fixed in #324. Same issue is #323
