### ISSUE TITLE
Regression in Files app with non-UTF8 byte sequence file names

### ISSUE THREAD

**Issue by CSC-swesters** [OSC/ondemand#3295]
Hello OSC,

I stumbled upon a regression from this issue https://github.com/OSC/ondemand/issues/2624 in Open OnDemand version 3.0.3. The issue also reproduced in a nightly build I tried, `3.1.20231207-158369.75c3c72.nightly`.

In the Files app, if I attempt to visit a directory which has a file with non-UTF8 bytes in its name, there will be a fatal error, and as a user I won't see any files. There is an error pop-up to users saying "Internal server error".

Here are the logs from the fatal event (from the nightly environment):

```
App 140382 output: [2024-01-11 18:36:14 +0200 ] ERROR "undefined local variable or method `stats' for #<PosixFile:0x00007f6c426e4c58 @path=#<Pathname:/users/username/ood-reproduce-non-utf8-name/\xFF\u0001\u0002\u0003-ood-test-file>, @stat=#<File::Stat dev=0xc26ac9c8, ino=144118416431716013, mode=0100664, nlink=1, uid=REDACTED, gid=REDACTED, rdev=0x0, size=12, blksize=4194304, blocks=8, atime=2024-01-11 18:25:54 +0200, mtime=2024-01-11 18:25:54 +0200, ctime=2024-01-11 18:25:54 +0200>>\n\n    Rails.logger.warn(\"Not showing file '\#{stats[:name]}' because it is not a UTF-8 filename.\") unless valid\n                                           ^^^^^"
App 140382 output: [2024-01-11 18:36:14 +0200 ]  INFO "method=GET path=/pun/sys/dashboard/files/fs/users/username/ood-reproduce-non-utf8-name format=html controller=FilesController action=fs status=500 error='ActionView::Template::Error: source sequence is illegal/malformed utf-8' allocations=17542 duration=21.58 view=0.00"
App 140382 output: [2024-01-11 18:36:14 +0200 ] FATAL "ActionView::Template::Error (source sequence is illegal/malformed utf-8):\n    27: json.time Time.now.to_i\n    28: json.error_message alert if alert\n  \napp/views/files/index.json.jbuilder:30\napp/controllers/files_controller.rb:106:in `block (2 levels) in fs'\napp/controllers/files_controller.rb:99:in `rescue in fs'\napp/controllers/files_controller.rb:7:in `fs'"
App 140382 output: [2024-01-11 18:36:14 +0200 ]  INFO "method=GET path=/pun/sys/dashboard/500 format=json controller=ErrorsController action=internal_server_error status=500 error='ActionView::MissingTemplate: Missing template errors/internal_server_error, application/internal_server_error with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :md, :markdown, :jbuilder]}. Searched in:\n  * \"/etc/ood/config/apps/dashboard/views\"\n  * \"/var/www/ood/apps/sys/dashboard/app/views\"\n  * \"/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/ood_appkit-2.1.1/app/views\"\n' allocations=9896 duration=12.35 view=0.00"
App 140382 output: Error during failsafe response: Missing template errors/internal_server_error, application/internal_server_error with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :md, :markdown, :jbuilder]}. Searched in:
App 140382 output:   * "/etc/ood/config/apps/dashboard/views"
App 140382 output:   * "/var/www/ood/apps/sys/dashboard/app/views"
App 140382 output:   * "/opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/ood_appkit-2.1.1/app/views"
App 140382 output: 
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionview-6.1.7.6/lib/action_view/path_set.rb:48:in `find'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionview-6.1.7.6/lib/action_view/lookup_context.rb:127:in `find'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionview-6.1.7.6/lib/action_view/renderer/template_renderer.rb:45:in `determine_template'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionview-6.1.7.6/lib/action_view/renderer/template_renderer.rb:7:in `render'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionview-6.1.7.6/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionview-6.1.7.6/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionview-6.1.7.6/lib/action_view/rendering.rb:117:in `block in _render_template'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionview-6.1.7.6/lib/action_view/base.rb:273:in `in_rendering_context'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionview-6.1.7.6/lib/action_view/rendering.rb:116:in `_render_template'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/streaming.rb:218:in `_render_template'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionview-6.1.7.6/lib/action_view/rendering.rb:103:in `render_to_body'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/abstract_controller/rendering.rb:25:in `render'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/rendering.rb:36:in `render'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
App 140382 output:   /usr/share/ruby/benchmark.rb:311:in `realtime'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/activesupport-6.1.7.6/lib/active_support/core_ext/benchmark.rb:14:in `ms'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/instrumentation.rb:45:in `render'
App 140382 output:   /var/www/ood/apps/sys/dashboard/app/controllers/errors_controller.rb:32:in `block (2 levels) in internal_server_error'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/mime_responds.rb:214:in `respond_to'
App 140382 output:   /var/www/ood/apps/sys/dashboard/app/controllers/errors_controller.rb:30:in `internal_server_error'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/abstract_controller/base.rb:228:in `process_action'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/rendering.rb:30:in `process_action'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/activesupport-6.1.7.6/lib/active_support/callbacks.rb:106:in `run_callbacks'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/abstract_controller/callbacks.rb:41:in `process_action'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/rescue.rb:22:in `process_action'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/activesupport-6.1.7.6/lib/active_support/notifications.rb:203:in `block in instrument'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/activesupport-6.1.7.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/activesupport-6.1.7.6/lib/active_support/notifications.rb:203:in `instrument'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/abstract_controller/base.rb:165:in `process'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionview-6.1.7.6/lib/action_view/rendering.rb:39:in `process'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal.rb:190:in `dispatch'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_controller/metal.rb:254:in `dispatch'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/
App 140382 output: action_dispatch/routing/route_set.rb:50:in `dispatch'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/routing/route_set.rb:33:in `serve'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/journey/router.rb:50:in `block in serve'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/journey/router.rb:32:in `each'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/journey/router.rb:32:in `serve'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/routing/route_set.rb:842:in `call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/middleware/show_exceptions.rb:53:in `render_exception'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/lograge-0.14.0/lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/railties-6.1.7.6/lib/rails/rack/logger.rb:26:in `block in call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:99:in `block in tagged'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:37:in `tagged'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/activesupport-6.1.7.6/lib/active_support/tagged_logging.rb:99:in `tagged'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/railties-6.1.7.6/lib/rails/rack/logger.rb:26:in `call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/middleware/request_id.rb:26:in `call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/rack-2.2.8/lib/rack/method_override.rb:24:in `call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/rack-2.2.8/lib/rack/runtime.rb:22:in `call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/middleware/executor.rb:14:in `call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/rack-2.2.8/lib/rack/sendfile.rb:110:in `call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/actionpack-6.1.7.6/lib/action_dispatch/middleware/host_authorization.rb:148:in `call'
App 140382 output:   /opt/ood/ondemand/root/usr/share/gems/3.0/ondemand/3.1.20231207-158369.75c3c72.nightly/gems/railties-6.1.7.6/lib/rails/engine.rb:539:in `call'
App 140382 output:   /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
App 140382 output:   /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
1704990974 2024 Jan 11 18:36:14 mahti-ood-future local6 notice ondemand_httpd  REDACTEDIP - username [11/Jan/2024:18:36:14 +0200] "GET /pun/sys/dashboard/files/fs//users/username/ood-reproduce-non-utf8-name HTTP/1.1" 500 182 "https://mahti-ood-future.csc.fi/pun/sys/dashboard/files/fs/users/username" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
App 140382 output:   /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 140382 output:   /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
App 140382 output:   /opt/rh/ondemand/root/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
unix: - - [11/Jan/2024:18:36:14 +0200] "GET /pun/sys/dashboard/files/fs//users/username/ood-reproduce-non-utf8-name HTTP/1.1" 500 193 "https://mahti-ood-future.csc.fi/pun/sys/dashboard/files/fs/users/username" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" "REDACTEDIP"
```

Hopefully this regression could be fixed before the next release!

**Comment by johrstrom** [comment]
That is unfortunate - yea I'll pick this up in 3.1.
