### ISSUE TITLE
3.1.9 seems to break the Shell app due to CSRF token issue

### ISSUE THREAD

**Issue by jjackzhn** [OSC/ondemand#3894]
After updating from 3.1.7 to 3.1.9, the shell app immediately crashes with the message:
```
Your connection to the remote server has been terminated.
```

Looking at the logs I found
```
App 4042244 output: Listening on 3000
App 4042244 output: Connection established
App 4042244 output: /var/www/ood/apps/sys/shell/app.js:161
App 4042244 output:   token = req.url.match(/csrf=([^&]*)/)[1];
App 4042244 output:                                        ^
App 4042244 output:
App 4042244 output: TypeError: Cannot read properties of null (reading '1')
App 4042244 output:     at WebSocketServer.connection (/var/www/ood/apps/sys/shell/app.js:161:40)
App 4042244 output:     at WebSocketServer.emit (node:events:517:28)
App 4042244 output:     at done (/var/www/ood/apps/sys/shell/app.js:233:9)
App 4042244 output:     at WebSocketServer.completeUpgrade (/var/www/ood/apps/sys/shell/node_modules/ws/lib/websocket-server.js:435:5)
App 4042244 output:     at WebSocketServer.handleUpgrade (/var/www/ood/apps/sys/shell/node_modules/ws/lib/websocket-server.js:343:10)
App 4042244 output:     at Server.upgrade (/var/www/ood/apps/sys/shell/app.js:232:7)
App 4042244 output:     at Server.emit (node:events:517:28)
App 4042244 output:     at onParserExecuteCommon (node:_http_server:939:14)
App 4042244 output:     at onParserExecute (node:_http_server:825:3) 
```

I made it print out `req.url` and it's the bare URL to the shell app without a CSRF token.

3.1.7 does not have this issue since downgrading fixes it.

**Comment by johrstrom** [comment]
I can't replicate. Note that it's the javascript making this network call with a CSRF token, not the original URL you put in your browser.

Here's an image of my console tab for the same. You'll note that the first request is what you enter in the URL (and the response is an html page), then later the browser makes another request to basically the same URL only with `wss` protocol instead of http.

![image](https://github.com/user-attachments/assets/bb53340f-312b-4f28-ae25-5020132c996d)

**Comment by johrstrom** [comment]
Didn't mean to close the ticket, only comment on it.  Can you show a similar network tab?

I double checked the diff between the two versions this morning and can't find/see how the ping pong change changed/broke functionality to that point.

I'd also ask if you can try 3.1.9 with a private window or after clearing your cache to see if that's any different.

https://github.com/OSC/ondemand/compare/v3.1.7...v3.1.9

**Comment by johrstrom** [comment]
Given the changelog, I'd pin this on updates we had to make to our lua code to support the latest version of httpd (or apache2 as the case may be). What apache2/httpd version are you using?

**Comment by jjackzhn** [comment]
Here's a screenshot - I do see both the original request and the follow-up wss request.
![ood-csrf](https://github.com/user-attachments/assets/ef7f33f4-4dbd-4ff8-9b61-234d20e52f6c)

I'm seeing the same behavior with incognito after clearing cache and doing a hard reload.

We are using httpd 2.4.37 from RHEL 8.

**Comment by jjackzhn** [comment]
Quite a few reds and oranges in the console...
![ood-console](https://github.com/user-attachments/assets/cb3794cb-559c-4306-a86a-0855d1a9262c)

**Comment by johrstrom** [comment]
Unfortunately I can't replicate on Rocky 8.8. Even 8.8 has `httpd-2.4.37-65`. I'll try to track down a system that has `httpd-2.4.37-56`, but I'm guessing the fixes we put in place for `2.4.62` somehow broke `httpd-2.4.37-56` (assuming that's the version you're on). 

I'll also have to look into the difference between those 56 and 65 releases.

**Comment by jjackzhn** [comment]
Yes, I have 2.4.37-56. I'll also try to find something different to test on.

**Comment by johrstrom** [comment]
Is it possible to update httpd? I'm unable to get an OS with that version. Everything on appstream has been updated.

I assume you're on some EL/8.8 variant?

**Comment by treydock** [comment]
@johrstrom You can enable the Vault for Rocky to get older packages, ie: https://dl.rockylinux.org/vault/rocky/8.8/AppStream/x86_64/os/Packages/h/.  Has https://dl.rockylinux.org/vault/rocky/8.8/AppStream/x86_64/os/Packages/h/httpd-2.4.37-56.module%2Bel8.8.0%2B1456%2Bd0a01c5e.7.x86_64.rpm.

You can inject this URL into something like `/etc/yum.repos.d/Rocky-AppStream.repo` and comment out `mirrorlist` and set the Vault URL at https://dl.rockylinux.org/vault/rocky/8.8/AppStream/x86_64/os/ to the value for `baseurl`.

**Comment by johrstrom** [comment]
> @johrstrom You can enable the Vault for Rocky to get older packages

Thanks, I'll take a look at it.

**Comment by johrstrom** [comment]
OK I can replicate if I downgrade back to `2.4.37-56`. It is infact coming from the lua updates we made to support `2.4.62`...

**Comment by johrstrom** [comment]
But that brings another question - If I have to install the version from the vault should we even support it? Is there a way to safely require `httpd >= 2.4.37-56`? The patch numbers could vary from distro to distro in theory, but do they in practice?

**Comment by treydock** [comment]
Latest versions for EL8:

Rocky 8 - 2.4.37-65
Alma 8 - 2.4.37-65
RHEL 8 - 2.4.37-65

The checksum and other parts of the appstream release do differ but I think for RHEL8 (and 9 most likely) we could require a minimum release based on what works with OnDemand.

Where this could run into issues is folks on RHEL 8 can pin to like RHEL 8.8 and if we were to require something from RHEL 8.10, that would break for them but also if that requirement is based on what works for OnDemand, they have no choice but to upgrade.

If `2.4.37-56` is the issue I think we'd have to say:

```
Requires: > 2.4.37-56 < 2.5
```

https://github.com/OSC/ondemand-packaging/blob/f777543e6818c47063ab1c1f4287493b32b634cb/packages/ondemand-runtime/rpm/ondemand-runtime.spec#L108

**Comment by johrstrom** [comment]
I found these 2 advisories, so I'm a bit convinced we should just require that `-65` patch version. I can't imagine someone saying `yes I need pin httpd to this version with known security advisories against it` - and if so, then they can just stay on 3.1.7?

https://access.redhat.com/errata/RHSA-2024:5193
https://access.redhat.com/errata/RHSA-2024:4197

**Comment by johrstrom** [comment]
> Sounds like a plan. I'll update to RHEL 8.10.

You don't need to fully upgrade to 8.10. Just an update to `httpd` should suffice.

**Comment by jjackzhn** [comment]
We have a mixture of RHEL 8.8 EUS, RHEL 8.10 and RHEL/Rocky 9.4; this would be a good reason to move things off 8.8 EUS anyway :)

**Comment by treydock** [comment]
> How can I test pinning the OS to 8.8?

This is done with subscription manager on RHEL systems as RHEL provides minor release repos.  The only way to stay on a minor release on Rocky that is not the latest minor release would be to start with 8.8 container then replace all repos with 8.8 Vault URLs.

On RHEL you'd do

```
sudo subscription-manager release --set=8.8
```

Which would update the repo URLs in `/etc/yum.repos.d/redhat.repo`.  I don't think this really works with Rocky/Alma since subscription-manager is designed to talk to RedHat systems about the system's valid subscription with RedHat.

**Comment by johrstrom** [comment]
I see. Yea then a locked RHEL 8.8 system won't support 3.1.9.  Hrrrrm. OK that may just be the best we can do. I can't figure out how to get the apache version in lua without shelling out a `rpm -q httpd` query and parsing it or similar which seems very complicated and moreover would slow down basically every request. So much so that it seems untenable.

**Comment by johrstrom** [comment]
> Rocky 9.4 host with httpd-2.4.57-8.el9.x86_64

It certainly does matter because that means specifying `Requires: > 2.4.37-56 < 2.5` isn't a silver bullet I thought it may be.

**Comment by treydock** [comment]
> It certainly does matter because that means specifying `Requires: > 2.4.37-56 < 2.5` isn't a silver bullet I thought it may be.

We can have RHEL8 and RHEL9 specific requirements.  We already do that for things like NodeJS because of different versions available: 

https://github.com/OSC/ondemand-packaging/blob/8abf784f09b65b1392651fd0694155d62b8d0e29/packages/ondemand-runtime/rpm/ondemand-runtime.spec#L88-L96

My guess is whatever patch RedHat backported, it was applied to 2.4.37 for RHEL8 and 2.4.57 for RHEL9 as RHEL tends to pin their software versions though less so with AppStream

**Comment by treydock** [comment]
So we could do

```
%if 0%{?rhel} == 8
Requires: %{apache} > 2.4.37-56, %{apache} < 2.5
...
%endif
%if 0%{?rhel} == 9
Requires: %{apache} > 2.4.57-8, %{apache} < 2.5
...
%endif
```

**Comment by Xaraxia** [comment]
I am having this issue, with the following installation:

httpd-2.4.37-65.module+el8.10.0+1830+22f0c9e0.x86_64

$ cat /etc/redhat-release 
Rocky Linux release 8.10 (Green Obsidian)

`App 2203442 output: /var/www/ood/apps/sys/shell/app.js:161
App 2203442 output:   token = req.url.match(/csrf=([^&]*)/)[1];
App 2203442 output:                                        ^
App 2203442 output: 
App 2203442 output: TypeError: Cannot read properties of null (reading '1')
App 2203442 output:     at WebSocketServer.connection (/var/www/ood/apps/sys/shell/app.js:161:40)
App 2203442 output:     at WebSocketServer.emit (node:events:517:28)
App 2203442 output:     at done (/var/www/ood/apps/sys/shell/app.js:233:9)
App 2203442 output:     at WebSocketServer.completeUpgrade (/var/www/ood/apps/sys/shell/node_modules/ws/lib/websocket-server.js:435:5)
App 2203442 output:     at WebSocketServer.handleUpgrade (/var/www/ood/apps/sys/shell/node_modules/ws/lib/websocket-server.js:343:10)
App 2203442 output:     at Server.upgrade (/var/www/ood/apps/sys/shell/app.js:232:7)
App 2203442 output:     at Server.emit (node:events:517:28)
App 2203442 output:     at onParserExecuteCommon (node:_http_server:939:14)
App 2203442 output:     at onParserExecute (node:_http_server:825:3)
App 2203442 output: 
App 2203442 output: Node.js v18.20.2
`

**Comment by Xaraxia** [comment]
From the browser it looks fine:

token = window.urlWithToken().match(/csrf=([^&]*)/)[1];
'AVPiWh3i-OEzDDpVlDgafakedatafakedata'
window.urlWithToken()
'wss://bunya-ondemand.rcc.uq.edu.au/pun/sys/shell/ssh/bunya.rcc.uq.edu.au?csrf=AVPiWh3i-OEzDDpVlDgafakedatafakedata'

So, potentially, something is preventing the token from being passed back to nodejs.

**Comment by johrstrom** [comment]
> So, potentially, something is preventing the token from being passed back to nodejs or otherwise mangling that URL in such a way that it is not being detected correctly.

The update to apache should have resolved this... Did you bounce apache after updating to ensure that the new version is running? That's the only thing I can think of. I know for sure this issue is caused by the `3.1.9` update using a version of apache that's lower than `httpd-2.4.37-65` (what you've reported to have).

**Comment by Xaraxia** [comment]
Yes, and I just did a systemctl restart again to be on the safe side.

11:40 sbw@bunya-ondemand:~$ rpm -qa | grep httpd
httpd-filesystem-2.4.37-65.module+el8.10.0+1830+22f0c9e0.noarch
httpd-devel-2.4.37-65.module+el8.10.0+1830+22f0c9e0.x86_64
httpd-2.4.37-65.module+el8.10.0+1830+22f0c9e0.x86_64
httpd-tools-2.4.37-65.module+el8.10.0+1830+22f0c9e0.x86_64
rocky-logos-httpd-86.3-1.el8.noarch

11:41 sbw@bunya-ondemand:~$ sudo /usr/sbin/httpd -v
Server version: Apache/2.4.37 (Rocky Linux)
Server built:   Jul  1 2024 14:01:13

**Comment by johrstrom** [comment]
No issues in delay. I'm not at SC personally, but many people from OSC are there at the OSC booth.

**Comment by Xaraxia** [comment]
Is it possible that there is an issue with the gems? We've got multiple packages installed for some reason, instead of just the latest. Should I remove them?

09:18 sbw@bunya-ondemand:/etc/yum.repos.d$ rpm -qa | grep ondemand
ondemand-3.1.9-1.el8.x86_64
ondemand-passenger-6.0.20-1.ood3.1.5.el8.x86_64
ondemand-release-web-3.0-1.noarch
ondemand-runtime-3.1.5-1.el8.x86_64
ondemand-ruby-3.1.5-1.el8.x86_64
ondemand-nginx-1.24.0-1.p6.0.20.ood3.1.5.el8.x86_64
ondemand-nodejs-3.1.5-1.el8.x86_64
ondemand-apache-3.1.5-1.el8.x86_64
ondemand-gems-3.1.9-1-3.1.9-1.el8.x86_64
ondemand-gems-3.0.3-1-3.0.3-1.el8.x86_64
ondemand-selinux-3.1.9-1.el8.x86_64
ondemand-gems-3.1.1-1-3.1.1-1.el8.x86_64
ondemand-gems-3.0.1-1-3.0.1-1.el8.x86_64

**Comment by johrstrom** [comment]
Yea I  don't think the gems are the issue here. What's the checksum of the httpd binary? Something like `md5sum $(which httpd)`. There has to be something obvious here we're missing because obviously the httpd I can get in a Rocky 8.4 container is somehow different than your Rocky 8.4 machine.

**Comment by Xaraxia** [comment]
Okay, we have done a complete reinstall, fresh version of OOD 4 on a brand new VM. Still suffering this problem!

`App 61623 output: Listening on 3000
App 61623 output: Connection established
App 61623 output: /var/www/ood/apps/sys/shell/app.js:161
App 61623 output:   token = req.url.match(/csrf=([^&]*)/)[1];
App 61623 output:                                        ^
App 61623 output: 
App 61623 output: TypeError: Cannot read properties of null (reading '1')
App 61623 output:     at WebSocketServer.connection (/var/www/ood/apps/sys/shell/app.js:161:40)
App 61623 output:     at WebSocketServer.emit (node:events:518:28)
App 61623 output:     at done (/var/www/ood/apps/sys/shell/app.js:233:9)
App 61623 output:     at WebSocketServer.completeUpgrade (/var/www/ood/apps/sys/shell/node_modules/ws/lib/websocket-server.js:436:5)
App 61623 output:     at WebSocketServer.handleUpgrade (/var/www/ood/apps/sys/shell/node_modules/ws/lib/websocket-server.js:344:10)
App 61623 output:     at Server.upgrade (/var/www/ood/apps/sys/shell/app.js:232:7)
App 61623 output:     at Server.emit (node:events:518:28)
App 61623 output:     at onParserExecuteCommon (node:_http_server:936:14)
App 61623 output:     at onParserExecute (node:_http_server:837:3)
App 61623 output: 
App 61623 output: Node.js v20.12.2
[ W 2025-02-11 18:11:00.0159 38825/T4 age/Cor/App/Poo/AnalyticsCollection.cpp:102 ]: Process (pid=61623, group=/var/www/ood/apps/sys/shell (production)) no longer exists! Detaching it from the pool.
[ N 2025-02-11 18:11:00.0160 38825/T4 age/Cor/CoreMain.cpp:1148 ]: Checking whether to disconnect long-running connections for process 61623, application /var/www/ood/apps/sys/shell (production)
`

**Comment by Xaraxia** [comment]
I'm not sure if it is relevant, but file downloads and job listing is ALSO broken, and has been in both 3.1.0 and 4.0.0 (the former upgraded from 3.0, the latter a new install but with the same configuration).

**Comment by johrstrom** [comment]
I'm sure that it's the `httpd` version that's the issue. `3.1.7` I believe is the last version that worked correctly with your apache HTTPD version.

Is there any way to update your apache HTTPD?

**Comment by Xaraxia** [comment]
I guess I could build it from source. Does this mean that OOD no longer supports Rocky 8 at all? I have Rocky 8.10 with the latest available httpd installed and this is listed as supported on [your installation page](https://osc.github.io/ood-documentation/latest/installation/install-software.html).

[sbw@bunya-ondemand ~]$ md5sum /usr/sbin/httpd
51c73d18ca7b9493ddd420e8dca2740e  /usr/sbin/httpd
[sbw@bunya-ondemand ~]$ sudo httpd -V
Server version: Apache/2.4.37 (Rocky Linux)
Server built:   Jul  1 2024 14:01:13
Server's Module Magic Number: 20120211:83
Server loaded:  APR 1.6.3, APR-UTIL 1.6.1
Compiled using: APR 1.6.3, APR-UTIL 1.6.1
Architecture:   64-bit
Server MPM:     event
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="run/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

**Comment by johrstrom** [comment]
EL8 should be fine, we run RHEL 8, but I believe it's the httpd that's not quite right. Here's the info from ours on a RHEL 8.10.

```
[johrstrom ~()] 🐍  md5sum /usr/sbin/httpd 
9b84faba1d41d636f1e87285b9bd082a  /usr/sbin/httpd
[johrstrom ~()] 🐬  rpm -q httpd
httpd-2.4.37-65.module+el8.10.0+22196+d82931da.2.x86_64
```

**Comment by Xaraxia** [comment]
```
[sbw@bunya-ondemand ~]$ rpm -q httpd
httpd-2.4.37-65.module+el8.10.0+1830+22f0c9e0.x86_64

```
It looks like your build may be marginally newer, but this is the one that comes with Rocky 8.10. Are you thinking that they backported something into that one that isn't in the Rocky one?

**Comment by johrstrom** [comment]
> Are you thinking that they backported something into that one that isn't in the Rocky one?


They must have, what we test against for EL8 is `2.4.37-65.module_el8.10.0+3874+c2064c23.2` which also appears slightly higher than what you have. IIRC we use AlmaLinux 8 to test. 

https://github.com/OSC/ondemand/actions/runs/13299275394/job/37137625824#step:5:533

**Comment by Xaraxia** [comment]
ARGH. Can confirm. We had a July build. Just ran updates to latest, and it's working now.

**Comment by nuttapongc** [comment]
Hi,
I found same issues. my host details
```
OS: RHEL 9.2
httpd: httpd-2.4.57-8.el9.x86_64
ondemand: ondemand-4.0.3-1.el9.x86_64
```

Could you please suggest?

Sincerely yours,
Toto

**Comment by johrstrom** [comment]
There should be more patches beyond `httpd: httpd-2.4.57-8.el9.x86_64` for you on EL9. I think you just need to update this.

**Comment by nuttapongc** [comment]
My httpd was updated to httpd-2.4.62-4.el9.x86_64 and my active job is working fine!. But on shell it show like No clusters defined.



Update
It's my fault in typo. now everything is work!
Thanks
Toto

**Comment by johrstrom** [comment]
So sorry for all the issues that this update has caused everyone. We feel like this is resolved now that httpd updates have filtered out to all the RHEL like distributions. 

Again, I apologize for all the issues that this has caused. We're going to close this now as solved as an update to httpd should have resolved the issues.
