### ISSUE TITLE
Upgrade dependencies to rh-git29 rh-ruby24 rh-nodejs6

### ISSUE THREAD

**Issue by ericfranz** [OSC/ondemand#4]
I started setting up a development environment to test and fix the apps for this on webdev02 by editing /etc/ood/profile:

```diff
-source scl_source enable nginx16 rh-passenger40 rh-ruby22 nodejs010 git19
+source scl_source enable nginx16 rh-passenger40 rh-git29 rh-nodejs6 rh-ruby24
```

* **NOTE: we will need to either remove or update /etc/ood/profile from all of the web nodes for the new rpm to work correctly, or else we will be loading older dependencies**

The first thing I notice is that whenever I run `gem list` I see these warnings:

```
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Ignoring redcarpet-3.2.3 because its extensions are not built.  Try: gem pristine redcarpet --version 3.2.3
Ignoring therubyracer-0.12.2 because its extensions are not built.  Try: gem pristine therubyracer --version 0.12.2
```

* I think these will go away if I install the individual rpms for each, though when I do `gem list` I see these in the list... after I do `source scl_source enable rh-git29 rh-nodejs6 rh-ruby24 rh- ror50` I see fewer errors:

   ```
    Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
    Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
    Ignoring redcarpet-3.2.3 because its extensions are not built.  Try: gem pristine redcarpet --version 3.2.3
    Ignoring therubyracer-0.12.2 because its extensions are not built.  Try: gem pristine therubyracer --version 0.12.2
    ```

Nokogiri failed to build when attempting to run this command on the master branch of the dashboard:

```
$ source scl_source enable rh-git29 rh-nodejs6 rh-ruby24
$ RAILS_ENV=production bin/setup
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Ignoring redcarpet-3.2.3 because its extensions are not built.  Try: gem pristine redcarpet --version 3.2.3
Ignoring therubyracer-0.12.2 because its extensions are not built.  Try: gem pristine therubyracer --version 0.12.2
cd /users/PZS0645/wiag/ood_portals/ondemand_test/sys/dashboard

== Building Dashboard App ==
RAILS_ENV               = production
RAILS_RELATIVE_URL_ROOT = /pun/sys/dashboard

== Installing dependencies ==
bin/bundle install --path=vendor/bundle
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Ignoring redcarpet-3.2.3 because its extensions are not built.  Try: gem pristine redcarpet --version 3.2.3
Ignoring therubyracer-0.12.2 because its extensions are not built.  Try: gem pristine therubyracer --version 0.12.2
Fetching gem metadata from https://rubygems.org/..............
Fetching rake 12.3.1
Installing rake 12.3.1
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching i18n 0.9.5
Installing i18n 0.9.5
Fetching minitest 5.11.3
Installing minitest 5.11.3
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.5
Installing tzinfo 1.2.5
Fetching activesupport 4.2.10
Installing activesupport 4.2.10
Fetching builder 3.2.3
Installing builder 3.2.3
Fetching erubis 2.7.0
Installing erubis 2.7.0
Fetching mini_portile2 2.3.0
Installing mini_portile2 2.3.0
Fetching nokogiri 1.8.4
Installing nokogiri 1.8.4 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /users/PZS0645/wiag/ood_portals/ondemand_test/sys/dashboard/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.4/ext/nokogiri
/opt/rh/rh-ruby24/root/usr/bin/ruby -r ./siteconf20180921-123756-dmqba5.rb extconf.rb
mkmf.rb can't find header files for ruby at /opt/rh/rh-ruby24/root/usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /users/PZS0645/wiag/ood_portals/ondemand_test/sys/dashboard/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.4 for inspection.
Results logged to /users/PZS0645/wiag/ood_portals/ondemand_test/sys/dashboard/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/nokogiri-1.8.4/gem_make.out

An error occurred while installing nokogiri (1.8.4), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.8.4'` succeeds before bundling.

In Gemfile:
  ood_appkit was resolved to 1.0.3, which depends on
    rails was resolved to 4.2.10, which depends on
      actionmailer was resolved to 4.2.10, which depends on
        actionpack was resolved to 4.2.10, which depends on
          actionview was resolved to 4.2.10, which depends on
            rails-dom-testing was resolved to 1.0.9, which depends on
              nokogiri
/opt/rh/rh-ruby24/root/usr/share/gems/gems/rake-12.0.0/lib/rake/file_utils.rb:66:in `block in create_shell_runner': Command failed with status (5): [bin/bundle install --path=vendor/bundle...] (RuntimeError)
	from /opt/rh/rh-ruby24/root/usr/share/gems/gems/rake-12.0.0/lib/rake/file_utils.rb:56:in `sh'
	from bin/setup:46:in `block in <main>'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/fileutils.rb:120:in `chdir'
	from /opt/rh/rh-ruby24/root/usr/share/ruby/fileutils.rb:120:in `cd'
	from /opt/rh/rh-ruby24/root/usr/share/gems/gems/rake-12.0.0/lib/rake/file_utils_ext.rb:37:in `chdir'
	from bin/setup:36:in `<main>'
```

I then did two things:

1. Updated ~wiag/.bash_profile to auto load rh-git29, rh-nodejs6, and rh-ruby24
2. sudo yum install rh-ruby22-ruby-devel

Now the dashboard (including nokogiri) builds successfully, though I still see these warnings:

```
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
Ignoring nokogiri-1.6.7.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.7.2
Ignoring redcarpet-3.2.3 because its extensions are not built.  Try: gem pristine redcarpet --version 3.2.3
Ignoring therubyracer-0.12.2 because its extensions are not built.  Try: gem pristine therubyracer --version 0.12.2
```

And I'm able to access the Dashboard!

* Lesson: **All Rails apps will definitely need rebuilt.**

**Comment by ericfranz** [comment]
See guidelines on https://osu.app.box.com/notes/247714301244 and https://osu.app.box.com/notes/254967536901 for upgrading. Some of these notes are not relevant since we have an rpm now.

**Comment by ericfranz** [comment]
Relevant points:

1. nginx_stage needs updated to use the new packages (appears in one location in `sbin/nginx_stage`)
2. nginx_stage needs updated to not use Fixnum/Bignum and instead Integer (though so far things seem to be working as is...)
3. https://github.com/OSC/ood-dashboard/blob/d6833b7e7f73c0f3eacc06e53cf5c9955bf4604a/app/views/products/show.html.erb#L54-L58
4. READMEs of apps that mention old SCLs need updated
5. All apps rebuilt

**Comment by ericfranz** [comment]
6. ood-portal-generator updated https://github.com/OSC/ood-portal-generator/blob/master/bin/generate#L4

**Comment by ericfranz** [comment]
Done
