### ISSUE TITLE
Implementing saml through mod_auth_mellon non-existent user error

### ISSUE THREAD

**Issue by lebonez** [OSC/ondemand#450]
I have implemented mod_auth_mellon without any issues with users that exist on the system. I am trying to implementing a better solution for users that do not have a local account and the page they see right now. They are shown a 500 status page. This is the error below. What options do I have. I am willing to write some code in getpwuid. I am unfamiliar with ruby. I tried doing a rescue statement in order to catch ArgumentError but it just ignores that anyways.
`
App 23937 output: [2020-03-27 12:46:33 +0000 ]  INFO "method=GET path=/pun/sys/dashboard/ format=html controller=DashboardController action=index status=500 error='ArgumentError: can't find user for 87502' duration=0.38 view=0.00"
App 23937 output: [2020-03-27 12:46:33 +0000 ] FATAL "ArgumentError (can't find user for 87502):\n  app/controllers/application_controller.rb:15:in `new'\n  app/controllers/application_controller.rb:15:in `set_user'"
App 23937 output: [2020-03-27 12:46:33 +0000 ]  INFO "method=GET path=/pun/sys/dashboard/500 format=html controller=ErrorsController action=internal_server_error status=500 error='ArgumentError: can't find user for 87502' duration=0.24 view=0.00"
App 23937 output: Error during failsafe response: can't find user for 87502
App 23937 output:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/2.4.0/gems/ood_support-0.0.3/lib/ood_support/user.rb:35:in `getpwuid'
`

**Comment by lebonez** [comment]
Ideally i'd like to at least give them a 403 page or even better render an informative page saying to request an account.

**Comment by johrstrom** [comment]
Yea I think I agree that's a bad user experience and redirecting to an account request page (something sites can override and make their own) is the right way to go.

Thanks for the ticket!

**Comment by lebonez** [comment]
I agree! I do have one update I think when I was testing with my account after removing from passwd it was giving me the 500 error. Here is the error with a fresh account.

Would be nice to change this page.

Error -- user doesn't exist: {someuser}
Run 'nginx_stage --help' to see a full list of available command line options.

 Also I was wondering where I can post the instructions for Azure AD saml (or possibly any mod_auth_mellon solution) for other people to use. It was definitely not an easy process :)

**Comment by johrstrom** [comment]
Hi sorry for the delay, I'm just circling back to this trying to clean out our triage.

As to the documentation about Azure AD saml, I would say post the information as a topic on https://discourse.osc.edu.  And maybe even open a ticket on [our documentation repo](https://github.com/OSC/ood-documentation) to include `mod_auth_mellon` if we don't already include it. 


As to the actual topic of this ticket. We have a `/register` API that you can configure to register new users. But, I'm not sure how (or if) we redirect to it, maybe folks had to navigate there.

Either way, I think we should catch the unknown user exception and redirect to a default page, or the register url if it exists. This is similar to how we deal with users with no home directories. We're able to catch that, and show a more user friendly page (that's also configurable).

**Comment by lebonez** [comment]
I want to put an update on this, I did finally figure out what is going on further down since I setup /register. The error was still happening even if I setup the user_map_fail to use the /register page. The underlying issue is mellon does not check if a user exists at the system level so it just returns the name-id no matter what. Then the user_map_cmd: '/opt/ood/ood_auth_map/bin/ood_auth_map.regex' command does nothing as well and just returns the username. I just changed user_map_cmd: to point to this script instead and now the /register loads if they don't exist system side.

#!/bin/bash
if id "$1" >/dev/null 2>&1; then
        echo "$1"
else
        echo ""
fi
