### ISSUE TITLE
Error when re-enable 1.3-like app dev for all 

### ISSUE THREAD

**Issue by kcgthb** [OSC/ondemand#71]
Hi!

I'm trying to re-enable app development for all users like it worked in 1.3, by un-commenting the alternative app_root block in `nginx_stage.yml`, as mentioned in the [docs](https://osc.github.io/ood-documentation/develop/app-development/enabling-development-mode.html#make-everyone-a-developer-by-default-optional):
https://github.com/OSC/ondemand/blob/ad4be2929565d23e195d5b54f61af411d88e6031/nginx_stage/share/nginx_stage_example.yml#L154-L157

When I do this, I get crashes with the following stack:
```
# /opt/ood/nginx_stage/sbin/nginx_stage
/opt/rh/rh-ruby24/root/usr/share/ruby/psych.rb:377:in `parse': (/etc/ood/config/nginx_stage.yml): mapping values are not allowed in this context at line 151 column 6 (Psych::SyntaxError)
        from /opt/rh/rh-ruby24/root/usr/share/ruby/psych.rb:377:in `parse_stream'
        from /opt/rh/rh-ruby24/root/usr/share/ruby/psych.rb:325:in `parse'
        from /opt/rh/rh-ruby24/root/usr/share/ruby/psych.rb:252:in `load'
        from /opt/rh/rh-ruby24/root/usr/share/ruby/psych.rb:473:in `block in load_file'
        from /opt/rh/rh-ruby24/root/usr/share/ruby/psych.rb:472:in `open'
        from /opt/rh/rh-ruby24/root/usr/share/ruby/psych.rb:472:in `load_file'
        from /opt/ood/nginx_stage/lib/nginx_stage/configuration.rb:468:in `read_configuration'
        from /opt/ood/nginx_stage/lib/nginx_stage/configuration.rb:461:in `set_default_configuration'
        from /opt/ood/nginx_stage/lib/nginx_stage/configuration.rb:385:in `extended'
        from /opt/ood/nginx_stage/lib/nginx_stage.rb:38:in `extend'
        from /opt/ood/nginx_stage/lib/nginx_stage.rb:38:in `<module:NginxStage>'
        from /opt/ood/nginx_stage/lib/nginx_stage.rb:25:in `<top (required)>'
        from /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/rh/rh-ruby24/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
```

I feel like I missed something, do you have any insight?

**Comment by ericfranz** [comment]
It looks like that commented out example is missing a colon. It should be

    app_root:

Not

    app_root

**Comment by kcgthb** [comment]
Duh, obviously, sorry for not noticing that and thanks for pointing it out.
I submitted #72 to fix a couple of those in the file, in case it could be helpful for someone else.
